print("hello")
print('kastamee idi kaasta')
print("akkada ikkada")
print("ekkada")
print("jana gana mana nenu evari mata vina")
print("ahrgagfiaef")
print("bro whatsupp")
print("fasjhbg")
print("l")
print("helooooooo")
print("bro whatsupp")
print("fasjhbg")
print("l")
print("hello")
print('kastamee idi kaasta')
print("Manas")
n=input()
print(n)
print("Bye")
print("P")
